### PR TITLE
Support node-version-file param

### PR DESCRIPTION
**Pull request by doniyor2109**
By default I have set `.nvmrc` file

### CODE REVIEW

**Comment by umidbekk** [comment]
I don't like the introduction of the extra property, it makes the API confusing, maybe it's better to use custom value for that, e.g:
```
- node-version: nvm
```

and in this case we will parse the nvmrc file?

**Comment by doniyor2109** [comment]
@umidbekk Yea, make sense. I introduced this field as base `actions/setup-node@v2` action supports that. 
I will update PR then.

**Comment by umidbekk** [comment]
> @umidbekk Yea, make sense. I introduced this field because base `actions/setup-node@v2` action supports that. 
> 
> I will update PR then.

@doniyor2109 oh, if it's supported, why didn't you simply pass this option to the setup node action?

**Comment by doniyor2109** [comment]
@umidbekk There is one problem with that. I wanted to set default value for `node-version-file` param and `node-version` has also default value. However original `actions/setup-node@v2` [says](https://github.com/actions/setup-node/blob/5b52f097d36d4b0b2f94ed6de710023fbb8b2236/docs/advanced-usage.md) which conflicts with current flow:

> The node-version-file input accepts a path to a file containing the version of Node.js to be used by a project, for example .nvmrc or .node-version. If both the node-version and the node-version-file inputs are provided then the node-version input is used.

**Comment by umidbekk** [comment]
@doniyor2109 so removal of `node-version` arg can help? it would be the breaking change, but will follow `setup-node` API

**Comment by doniyor2109** [comment]
@umidbekk Yea, it should solve. However there is one catch that if `node-version-file` is not found it will [throw error](https://github.com/actions/setup-node/blob/bacd6b4b3ac3127b28a1e1920c23bf1c2cadbb85/src/main.ts#L80-L89). So we cannot set default value for `node-version-file` as well

**Comment by umidbekk** [comment]
@doniyor2109 so you can use same rules as setup-node: https://github.com/actions/setup-node/blob/bacd6b4b3ac3127b28a1e1920c23bf1c2cadbb85/action.yml#L8-L11

**Comment by doniyor2109** [comment]
@umidbekk Ok. I initially wanted to make default value for `node-version-file` so we can write action without any params and just update `.nvmrc` file)

I want to make it like this, what do you think?

```js
let version, versionFile;

if (param.node_version) {
	version = param.node_version;
} else {
	versionFile = param.node_version || '.nvmrc';
}
```

**Comment by umidbekk** [comment]
@doniyor2109 You can skip both arguments in the `setup-node`, it will just use the existing `node` version, let's keep this simple :)

**Comment by doniyor2109** [comment]
Closing for now because of low importance

**Pull request closed without merging**
